version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  snyk-scan:
    docker:
      - image: cimg/node:lts
    steps:    
      - checkout
      - run: npm install
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: high
          token-variable: SNYK_TOKEN

workflows:
  build-snyk:
    jobs:
      - snyk-scan
